# SonarQube Project Configuration
sonar.projectKey=iot-access-sentinel
sonar.projectName=IoT-Access-Sentinel
sonar.projectVersion=1.0.0
sonar.sources=.,api,common,config,decision_engine,enforcer,observer,tools
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/*.html,**/*.css,**/*.js,**/venv/**,**/__pycache__/**,**/external_repos/**
sonar.test.inclusions=tests/**/*
sonar.sourceEncoding=UTF-8
